# Generated by Django 5.1.2 on 2024-11-20 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_fnr_st_email_and_more'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='est_in_idFornecedor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='est_st_quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='est_st_valor',
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('comp_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_in_quantidade', models.CharField(max_length=10)),
                ('comp_vl_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comp_dt_compra', models.DateField()),
                ('comp_in_idFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
                ('comp_in_idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
