# Generated by Django 5.1.2 on 2024-11-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='est_in_idFornecedor',
        ),
    ]
