# Generated by Django 5.1.2 on 2024-11-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_est_in_idfornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comp_in_quantidade',
            field=models.IntegerField(),
        ),
    ]
