# Generated by Django 5.1.2 on 2024-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_est_in_idfornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='est_st_quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='est_st_valor',
        ),
        migrations.AddField(
            model_name='compra',
            name='comp_in_quantidade',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='comp_in_valor',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
