# Generated by Django 5.1.2 on 2024-11-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('ins_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('ins_st_nome', models.CharField(max_length=30)),
                ('ins_in_quantidade', models.IntegerField()),
                ('ins_dt_aquisicao', models.DateField(blank=True, null=True)),
                ('ins_dt_validade', models.DateField(blank=True, null=True)),
                ('ins_in_valor', models.IntegerField()),
                ('ins_ch_status', models.CharField(max_length=1)),
                ('ins_dt_cadastro', models.DateField()),
                ('ins_in_fornecedor', models.IntegerField()),
            ],
        ),
    ]
