# Generated by Django 5.1.2 on 2024-10-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('frn_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('fnr_st_nome', models.CharField(max_length=30)),
                ('fnr_ch_tipo', models.CharField(max_length=1)),
                ('fnr_st_doc', models.CharField(max_length=18)),
                ('fnr_st_cep', models.CharField(blank=True, max_length=20, null=True)),
                ('fnr_st_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('fnr_st_email', models.CharField(max_length=50)),
            ],
        ),
    ]
