# Generated by Django 5.1.2 on 2024-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='frn_in_id',
            new_name='fnr_in_id',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='fnr_st_cep',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fnr_st_cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fnr_st_endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fnr_st_estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
