# Generated by Django 5.1.2 on 2024-11-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_rename_frn_in_id_fornecedor_fnr_in_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='fnr_st_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fnr_st_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fnr_st_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
