# Generated by Django 5.1.3 on 2024-11-23 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_cliente_cli_st_nome'),
        ('produtos', '0004_alter_compra_comp_dt_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendasProdutos',
            fields=[
                ('vend_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('vend_in_quantidade', models.IntegerField()),
                ('vend_vl_valorProduto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vend_in_idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('vend_in_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendas.vendasprodutos')),
                ('vend_vl_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vend_dt_venda', models.DateField(default=datetime.date.today)),
                ('vend_in_idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vend_in_idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
