# Generated by Django 5.1.3 on 2024-11-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='vend_in_idProduto',
        ),
        migrations.AddField(
            model_name='vendasprodutos',
            name='vend_in_idVenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendas.vendas'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='vend_in_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
