# Generated by Django 5.1.3 on 2024-11-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_plantar_plan_dt_plantar'),
        ('vendas', '0003_rename_vend_in_id_vendasprodutos_vend_in_id_produto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendasprodutos',
            old_name='vend_in_id_Produto',
            new_name='vend_in_id_tabela',
        ),
        migrations.AlterField(
            model_name='vendasprodutos',
            name='vend_in_idProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.plantar'),
        ),
    ]
