# Generated by Django 5.1.2 on 2024-10-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_st_nome', models.CharField(max_length=50)),
                ('cli_ch_tipo', models.CharField(max_length=1)),
                ('cli_st_doc', models.CharField(max_length=18)),
                ('cli_st_endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('cli_st_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cli_st_estado', models.CharField(blank=True, max_length=10, null=True)),
                ('cli_st_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cli_st_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
